import { Component, OnDestroy, OnInit, inject, signal } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { Subscription, firstValueFrom, timer } from 'rxjs';
import { AsyncStateComponent } from '../../../shared/components/async-state.component';
import { PageHeaderComponent } from '../../../shared/components/page-header.component';
import { formatCurrency } from '../../../shared/utils/formatters';
import { getErrorMessage } from '../../../shared/utils/http-error';
import { DashboardMetricCardComponent } from '../components/dashboard-metric-card.component';
import { RecentOrdersPanelComponent } from '../components/recent-orders-panel.component';
import { TopProductsPanelComponent } from '../components/top-products-panel.component';
import { DashboardApiService } from '../data-access/dashboard-api.service';
import type { DashboardProjection } from '../dashboard.models';

@Component({ selector:'app-dashboard-page', standalone:true, imports:[MatButtonModule,PageHeaderComponent,AsyncStateComponent,DashboardMetricCardComponent,TopProductsPanelComponent,RecentOrdersPanelComponent], styles:[`:host{display:block}.metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:16px;margin-bottom:16px}.panels{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}@media(max-width:959px){.panels{grid-template-columns:1fr}}`], template:`<app-page-header eyebrow="Overview" title="Dashboard" description="Live operational snapshot. Data refreshes directly every 30 seconds."><div pageActions><button mat-stroked-button (click)="load()" [disabled]="loading()">Refresh</button></div></app-page-header><app-async-state [loading]="loading()" [error]="error()" [showRetry]="true" (retry)="load()"/>@if(data();as dashboard){<section class="metrics"><app-dashboard-metric-card label="Revenue today" [value]="money(dashboard.revenueToday)" helper="Current day"/><app-dashboard-metric-card label="Revenue this month" [value]="money(dashboard.revenueThisMonth)" helper="Month to date"/><app-dashboard-metric-card label="Orders" [value]="dashboard.totalOrders"/><app-dashboard-metric-card label="Pending orders" [value]="dashboard.pendingOrders"/><app-dashboard-metric-card label="Products" [value]="dashboard.totalProducts"/><app-dashboard-metric-card label="Low stock" [value]="dashboard.lowStockProducts"/><app-dashboard-metric-card label="Employees" [value]="dashboard.totalEmployees"/></section><section class="panels"><app-top-products-panel [products]="dashboard.topProducts"/><app-recent-orders-panel [orders]="dashboard.recentOrders"/></section>}` })
export class DashboardPage implements OnInit,OnDestroy { readonly loading=signal(false); readonly error=signal<string|null>(null); readonly data=signal<DashboardProjection|null>(null); readonly money=formatCurrency; private readonly api=inject(DashboardApiService); private refresh?:Subscription; ngOnInit(){this.refresh=timer(0,30_000).subscribe(()=>void this.load());} ngOnDestroy(){this.refresh?.unsubscribe();} async load(){this.loading.set(true);this.error.set(null);try{this.data.set(await firstValueFrom(this.api.get()));}catch(error){this.error.set(getErrorMessage(error));}finally{this.loading.set(false);}} }
