<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TemplateApp.Infrastructure\TemplateApp.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <!--#if (database == "sqlserver") -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <!--#endif -->
    <!--#if (database == "postgresql") -->
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <!--#endif -->
  </ItemGroup>
</Project>
