set dotenv-load := true
set export := true

default:
    @just --list

restore:
    dotnet restore TemplateApp.sln

build:
    dotnet build TemplateApp.sln

test:
    dotnet test TemplateApp.sln

run:
#if (otel)
    dotnet run --project src/TemplateApp.AppHost
#else
    dotnet run --project src/TemplateApp.Api
#endif

init-db:
    dotnet ef migrations add InitialCreate --project src/TemplateApp.Infrastructure --startup-project src/TemplateApp.Migrations
    dotnet ef database update --project src/TemplateApp.Infrastructure --startup-project src/TemplateApp.Migrations

migrate name:
    dotnet ef migrations add {{name}} --project src/TemplateApp.Infrastructure --startup-project src/TemplateApp.Migrations

migrate-remove:
    dotnet ef migrations remove --project src/TemplateApp.Infrastructure --startup-project src/TemplateApp.Migrations

db-update:
    dotnet ef database update --project src/TemplateApp.Infrastructure --startup-project src/TemplateApp.Migrations

migrations:
    dotnet ef migrations list --project src/TemplateApp.Infrastructure --startup-project src/TemplateApp.Migrations

migration-script output="migrations.sql":
    dotnet ef migrations script --idempotent --output {{output}} --project src/TemplateApp.Infrastructure --startup-project src/TemplateApp.Migrations
