<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\TemplateApp.Domain\TemplateApp.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Mediator.Abstractions" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>
</Project>
